stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw

  data_processing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - data/raw
    - src/data/data_preprocessing.py
    outs:
    - data/processed

  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps:
    - data/processed
    - src/features/feature_engineering.py
    params:
    - feature_engineering.max_features
    outs:
    - data/features

  model_building:
    cmd: python src/models/model_building.py
    deps:
    - data/features
    - src/models/model_building.py
    params:
    - model_building.learning_rate
    - model_building.n_estimators
    - model_building.max_depth
    - model_building.eval_metric
    - model_building.use_label_encoder
    outs:
    - models/xgboost_model.pkl

  model_eval:
    cmd: python src/models/model_eval.py
    deps:
    - data/features
    - src/models/model_building.py
    - src/models/model_eval.py
    metrics:
    - metrics.json
