data_ingestion:
  test_size: 0.01

feature_engineering:
  max_features: 5000

model_building:
  learning_rate: 0.01
  n_estimators: 100
  max_depth: 3
  eval_metric: 'mlogloss'
  use_label_encoder: False